name: Video Generator

on:
  workflow_dispatch: # يسمح لك بتشغيل السكربت يدوياً بضغطة زر

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install FFmpeg and Node.js
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg nodejs

    - name: Install Dependencies
      run: |
        pip install requests nest_asyncio yt-dlp tqdm edge-tts

    - name: Run Script
      run: python main.py
